/**
 * @file index.js
 * @description Entry point for the Roulette API. 
 * Implements a decoupled architecture using Strategy and Dependency Injection patterns.
 * @version 1.0.0
 */

const express  = require('express');
const { exec } = require('child_process');
const path     = require('path');

/**
 * @interface RngProviderStrategy
 * @description Abstract base class defining the contract for random number generation strategies.
 * Follows the Strategy Pattern (GoF) to encapsulate algorithmic variations.
 */
class RngProviderStrategy {
    /**
     * @abstract
     * @returns {Promise<number>} A promise that resolves to a generated number.
     * @throws {Error} If the method is not implemented by a concrete subclass.
     */
    async generate() {
        throw new Error("Method 'generate()' must be implemented by a concrete strategy.");
    }
}

/**
 * @class CppBinaryStrategy
 * @extends RngProviderStrategy
 * @description Concrete implementation of RngProviderStrategy that executes a compiled C++ binary.
 * Handles Inter-Process Communication (IPC) via standard output (stdout).
 */
class CppBinaryStrategy extends RngProviderStrategy {
    /**
     * @param {string} binaryPath Absolute path to the executable binary.
     */
    constructor(binaryPath) {
        super();
        this.binaryPath = binaryPath;
    }

    /**
     * @override
     * @description Executes the binary and parses the numeric output.
     * @returns {Promise<number>}
     */
    async generate() {
        return new Promise((resolve, reject) => {
            exec(this.binaryPath, (error, stdout, stderr) => {
                if (error) {
                    return reject(new Error(`Binary Execution Failure: ${error.message}`));
                }
                if (stderr) {
                    return reject(new Error(`Binary Runtime Error: ${stderr}`));
                }
                
                const parsedValue = parseInt(stdout.trim(), 10);
                if (isNaN(parsedValue)) {
                    return reject(new Error("Invalid output received from RNG binary."));
                }
                
                resolve(parsedValue);
            });
        });
    }
}

/**
 * @class RouletteService
 * @description Domain service responsible for roulette business logic.
 * Implements Dependency Injection to receive an RNG strategy, following the Dependency Inversion Principle (SOLID).
 */
class RouletteService {
    /**
     * @param {RngProviderStrategy} rngStrategy The strategy to be used for number generation.
     */
    constructor(rngStrategy) {
        this.rngStrategy = rngStrategy;
    }

    /**
     * @description Orchestrates the rolling process and formats the result.
     * @returns {Promise<Object>} Object containing the result, timestamp, and metadata.
     */
    async roll() {
        const result = await this.rngStrategy.generate();
        return {
            success: true,
            data: {
                number: result,
                type  : typeof result === 'number' ? 'byte' : 'unknown',
                engine: "C++ High-Entropy Logic"
            },
            metadata: {
                timestamp: new Date().toISOString(),
                version  : "v1.0.0"
            }
        };
    }
}

/**
 * Application Bootstrapping
 * Handles initialization of services and routing.
 */
const app      = express();
const PORT     = process.env.PORT || 3000;
const BIN_PATH = path.join(__dirname, '../bin/rng_engine');

/**
 * Dependency Injection Layer
 * Concrete implementations are instantiated and injected into services.
 */
const rngStrategy     = new CppBinaryStrategy(BIN_PATH);
const rouletteService = new RouletteService(rngStrategy);

/**
 * @route GET /api/v1/roll
 * @description Returns a pseudo-random number generated by the underlying C++ engine.
 * Implements standard RESTful response patterns.
 */
app.get('/api/v1/roll', async (req, res) => {
    try {
        const payload = await rouletteService.roll();
        res.status(200).json(payload);
    } catch (error) {
        res.status(500).json({
            success: false,
            error: {
                message: "RNG_SERVICE_FAILURE",
                details: error.message
            }
        });
    }
});

/**
 * Server activation
 */
app.listen(PORT, () => {
    console.info(`[SYSTEM] Roulette API service initialized on port ${PORT}`);
    console.info(`[INFRA] RNG Binary Path: ${BIN_PATH}`);
});